dofile("helper.luac")
dofile("Component.luac")
dofile("Keyboard.luac")
dofile("TextureManager.luac")
dofile("Terrain.luac")
dofile("Audio.luac")
dofile("Launcher.luac")
dofile("component/RigidBody.luac")
dofile("component/Sprite.luac")
dofile("component/WarBehavior.luac")
dofile("component/BardBehavior.luac")
dofile("component/MagBehavior.luac")
dofile("component/CommonBehavior.luac")
dofile("component/UnitStatus.luac")
dofile("component/FlyingDeath.luac")
dofile("component/FallingDeath.luac")
dofile("component/FungiMove.luac")
dofile("component/Liftup.luac")
dofile("component/Suicide.luac")
dofile("component/KeyControl.luac")
dofile("component/SlidingBehavior.luac")
dofile("component/Pocket.luac")
dofile("component/ClimbLadder.luac")
dofile("component/BiggerFaster.luac")
dofile("component/MsgBox.luac")
dofile("component/GhostMove.luac")
dofile("component/CannotMove.luac")
dofile("component/Camp.luac")
dofile("component/CannonBehavior.luac")
dofile("component/MissileBehavior.luac")
dofile("component/ActionLog.luac")
dofile("component/Follow.luac")
dofile("component/DogMove.luac")
dofile("component/SlowJump.luac")

dofile("env.luac")

Hero        = dofile("entity/Hero.luac")
Enemy       = dofile("entity/Enemy.luac")
Spike       = dofile("entity/Spike.luac")
GiantRock   = dofile("entity/GiantRock.luac")
Grain       = dofile("entity/Grain.luac")
TrapTrigger = dofile("entity/TrapTrigger.luac")
MageShield  = dofile("entity/MageShield.luac")
ArrowTrap   = dofile("entity/ArrowTrap.luac")
Conveyer    = dofile("entity/Conveyer.luac")
Fx          = dofile("entity/Fx.luac")
Key         = dofile("entity/Key.luac")
Spring      = dofile("entity/Spring.luac")
HeavyBox    = dofile("entity/HeavyBox.luac")
Punch       = dofile("entity/Punch.luac")
Epic        = dofile("entity/Epic.luac")
Fireball    = dofile("entity/Fireball.luac")
Carrier     = dofile("entity/Carrier.luac")
Obstacle    = dofile("entity/Obstacle.luac")
StrayDog    = dofile("entity/StrayDog.luac")
Torch       = dofile("entity/Torch.luac")
BubbleWord  = dofile("entity/BubbleWord.luac")

dofile("Level.luac")
dofile("OP.luac")
dofile("CutScene.luac")
dofile("UI.luac")

dofile("main.luac")